### ISSUE TITLE
instructions

### ISSUE THREAD

**Issue by Jfaler** [regonn/kaggle-discord-bot#1]
What python and pip version do I need use to get this working? What are the commands to get this running without heroku? What do I do with the env.sample? Thank you.

```
$ python3 main.py
$ pip3 install -r requirements.txt
```

**Comment by regonn** [comment]
Thank you for trying.

I think this code runs any ptyhon3 and pip versions.

You need these environment values. If you use `dotenv`, please create `.env` from `.env.sample`.

```
# Now supports English(en) or Japanese(ja).
LOCALE='en'

# Discord
DISCORD_TOKEN=
DISCORD_CHANNEL_ID=

# These variables are needed for setting local environment variables when import kaggle-api.
# You can also place kaggle.json file in your root directory.
KAGGLE_USERNAME=
KAGGLE_KEY=

# If this key is not set, load dotenv values.
# PRODUCTION=True
```

**Comment by Jfaler** [comment]
Hey I now get this error when running the above commands.
```
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 29, in on_ready
    await channel.send(i18n.t(id='kaggle.hi', hour=now.hour))
AttributeError: 'NoneType' object has no attribute 'send'
```

**Comment by regonn** [comment]
I think your `DISCORD_CHANNEL_ID` is invalid.
Please make sure your discord bot joins your discord server.

**Comment by Jfaler** [comment]
![kaggle-bot-discord](https://user-images.githubusercontent.com/8336385/64137977-c33c7180-cdaf-11e9-8bc9-6ff5778c3777.png)
![error](https://user-images.githubusercontent.com/8336385/64137988-cb94ac80-cdaf-11e9-8ded-a92b8688e59a.png)
The channel ID was correct but the error still persists. When the bot first joins the channel is it supposed to list competitions?

**Comment by regonn** [comment]
> When the bot first joins the channel is it supposed to list competitions?

No, the bot post only when run `python main.py`.

I tried some situation. This error occurs when `DISCORD_CHANNEL_ID` is incorrect, and `channel` instance is set `None`

![コメント 2019-09-03 1122301](https://user-images.githubusercontent.com/1227891/64139901-874fed80-ce3d-11e9-9702-ec240b02a839.png)

If you get your channel id from here(Copy ID), I don't know any more information. Sorry.
![コメント 2019-09-03 112230](https://user-images.githubusercontent.com/1227891/64139965-c2522100-ce3d-11e9-83ab-876deab3eba2.png)

**Comment by Jfaler** [comment]
![kaggle-bot](https://user-images.githubusercontent.com/8336385/64140705-3c40c680-cdba-11e9-90cf-2928fcf9af2d.png)

Oh, I copied the servers ID instead of the channel ID and now it works. Awesome work on the bot and thanks for your help.

I was able to setup the script to execute in intervals of 1800 seconds with the command below.
```
watch - n 1800 python3 main.py
```
