### ISSUE TITLE
Heroku button is not working

### ISSUE THREAD

**Issue by Doarakko** [regonn/kaggle-discord-bot#2]
> The ‘Deploy to Heroku’ button enables users to deploy apps to Heroku without leaving the web browser
[Heroku: Creating a 'Deploy to Heroku' Button](https://devcenter.heroku.com/articles/heroku-button)

Need `app.json` to enable heroku button.

## Current state
- Heroku button
![](https://user-images.githubusercontent.com/21009186/67150061-d23e9b00-f2ed-11e9-9b1c-db106989cbf5.png)

- Push Heroku button
![](https://user-images.githubusercontent.com/21009186/67150026-52183580-f2ed-11e9-99ee-b1142792b839.png)

## Reference
- [Heroku: app.json Schema](https://devcenter.heroku.com/articles/app-json-schema)
- [Heroku: Creating a 'Deploy to Heroku' Button](https://devcenter.heroku.com/articles/heroku-button)

**Comment by regonn** [comment]
Thank you PR.
I tried the new button and it works properly.
